# Site settings
title: "CloverMeadows"
description: Clover Meadows Targhees

# modify version numbers below when upgrading bootstrap
# only the assets directory is needed from the bootstrap-sass download
bootstrap-sass: bootstrap-sass-3.3.7
sass:
    sass_dir: /bootstrap-sass-3.3.7/assets/stylesheets
    style: :compressed

kramdown:
  input: GFM
  hard_wrap: true
  toc_levels: "2"

timezone: US/Mountain

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md